### ISSUE TITLE
No funciona el instalador de dotly

### ISSUE THREAD

**Issue by juancamunoz** [CodelyTV/dotly#183]
```
history: Error during git clone
  remote: Repository not found.
  fatal: repositorio 'https://github.com/zimfw/history.git/' no encontrado
x /home/juanca/.zimrc:4:history: Not installed. Run zimfw install to install.
Failed to source /home/juanca/.zimrc

Installing completions
/home/juanca/.zshrc:source:12: no existe el archivo o el directorio: /home/juanca/.dotfiles/modules/dotly/modules/zimfw/init.zsh
```

Error al instalar dotly

**Comment by gtrabanco** [comment]
Hay que borrar o commentar (con `#`) en el `.zimrc` la línea `zmodule zimfw/history`

Esto se debe a que el repositorio https://github.com/zimfw/history ya no existe.

Si necesitas Dotly o algo equivalente ya, puedes usar mi fork.

---
You have to the delete or comment (by using `#`) in the `.zimrc` the line which says `zmodule zimfw/history`

This is because the repository https://github.com/zimfw/history currently does not exists.

If you need Dotly right now you can use my fork.

**Comment by JavierCane** [comment]
@gtrabanco PR merged into `master`. It should properly work if you try to install dotly again 🙂

Thanks a lot for reporting the issue and sorry for the inconveniences! 🙌
